package viewmodel

import (
	"reflect"
	"testing"
)

func TestPlanCommit(t *testing.T) {
	t.Parallel()
	disk := map[string][]byte{
		"same.svg":  []byte("S"),
		"stale.svg": []byte("old"),
		"gone.svg":  []byte("G"),
		"user.txt":  []byte("mine"),
	}
	onDisk := func(p string) ([]byte, bool) { b, ok := disk[p]; return b, ok }
	next := []Artifact{
		{Path: "stale.svg", Bytes: []byte("new")},
		{Path: "same.svg", Bytes: []byte("S")},
		{Path: "fresh.svg", Bytes: []byte("F")},
	}
	old := Manifest{Paths: []string{"gone.svg", "same.svg", "stale.svg"}}

	got := PlanCommit(old, next, onDisk)
	want := CommitPlan{
		Write:     []string{"fresh.svg", "stale.svg"},
		Unchanged: []string{"same.svg"},
		Remove:    []string{"gone.svg"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("PlanCommit = %+v, want %+v", got, want)
	}
}

func TestPlanCommitNeverRemovesUnownedFiles(t *testing.T) {
	t.Parallel()
	onDisk := func(string) ([]byte, bool) { return []byte("x"), true }
	// No manifest (first build, or a corrupt one read as empty): nothing is
	// owned, so nothing is removed even though files exist on disk.
	got := PlanCommit(Manifest{}, []Artifact{{Path: "a", Bytes: []byte("y")}}, onDisk)
	if got.Remove != nil {
		t.Errorf("Remove = %v, want nil", got.Remove)
	}
	if !reflect.DeepEqual(got.Write, []string{"a"}) {
		t.Errorf("Write = %v", got.Write)
	}
}

func TestManifestRoundTrip(t *testing.T) {
	t.Parallel()
	m := NewManifest([]Artifact{{Path: "b"}, {Path: "a"}})
	data := m.Encode([]string{"main.loko.hcl"})
	want := "# Code generated by loko from main.loko.hcl. DO NOT EDIT.\na\nb\n"
	if string(data) != want {
		t.Fatalf("Encode = %q, want %q", data, want)
	}
	back := DecodeManifest(data)
	if !reflect.DeepEqual(back.Paths, []string{"a", "b"}) {
		t.Errorf("DecodeManifest = %v", back.Paths)
	}
	// Corruption never widens ownership: unsafe lines are dropped.
	bad := DecodeManifest([]byte("# x\n../escape\n/abs\nok\n\n"))
	if !reflect.DeepEqual(bad.Paths, []string{"ok"}) {
		t.Errorf("DecodeManifest(bad) = %v", bad.Paths)
	}
}
