package viewmodel

import (
	"sort"
	"strings"
)

// NoticeText is the generated-file notice every artifact opens with (FR-020):
// "Code generated by loko from <sources>. DO NOT EDIT."
//
// sources are project-relative *.loko.hcl paths; they are sorted and
// de-duplicated. The text never contains a timestamp, a version or a host, so
// it cannot make two builds of the same input differ (FR-021).
//
// An absolute path panics: provenance only ever supplies project-relative
// paths, so one reaching here is a programming error that would leak a
// machine-specific string into committed output.
func NoticeText(sources []string) string {
	files := append([]string(nil), sources...)
	sort.Strings(files)
	files = dedupe(files)
	for _, f := range files {
		if strings.HasPrefix(f, "/") || strings.HasPrefix(f, `\`) || (len(f) > 1 && f[1] == ':') {
			panic("viewmodel: absolute source path in generated-file notice: " + f)
		}
	}
	if len(files) == 0 {
		return "Code generated by loko. DO NOT EDIT."
	}
	return "Code generated by loko from " + strings.Join(files, ", ") + ". DO NOT EDIT."
}
