package viewmodel

import (
	"reflect"
	"strings"
	"testing"
)

func TestSortViews(t *testing.T) {
	t.Parallel()
	vs := []View{
		{ID: "zeta", Kind: KindDeclaredView},
		{ID: "deployment-prod", Kind: KindDeploymentView},
		{ID: "system-b", Kind: KindSystemView},
		{ID: "container-a", Kind: KindContainerView},
		{ID: "alpha", Kind: KindDeclaredView},
		{ID: "system-a", Kind: KindSystemView},
		{ID: "landscape", Kind: KindLandscapeView},
	}
	SortViews(vs)
	var ids []string
	for _, v := range vs {
		ids = append(ids, string(v.ID))
	}
	want := "landscape system-a system-b container-a deployment-prod alpha zeta"
	if got := strings.Join(ids, " "); got != want {
		t.Errorf("SortViews = %s, want %s", got, want)
	}
}

// TestStyleFor pins every row of the research R6 convention table.
func TestStyleFor(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name        string
		role        NodeRole
		kind        string
		shape       Shape
		fill        string
		stroke      string
		dashed      bool
		wantClasses []string
	}{
		{"person", RoleElement, KindPerson, ShapePerson, "#08427b", "#073b6f", false, []string{"kind-person"}},
		{"system", RoleElement, KindSystem, ShapeRectangle, "#1168bd", "#0b4884", false, []string{"kind-system"}},
		{"container", RoleElement, KindContainer, ShapeRectangle, "#438dd5", "#3c7fc0", false, []string{"kind-container"}},
		{"component", RoleElement, KindComponent, ShapeRectangle, "#85bbf0", "#78a8d8", false, []string{"kind-component"}},
		{"external", RoleElement, KindExternal, ShapeRectangle, "#999999", "#8a8a8a", true, []string{"external", "kind-external"}},
		{"instance takes its kind", RoleInstance, KindContainer, ShapeRectangle, "#438dd5", "#3c7fc0", false, []string{"kind-container"}},
		{"subject boundary", RoleSubject, KindSystem, ShapeBoundary, "", "#444444", true, []string{"kind-system"}},
		{"group boundary", RoleGroup, "", ShapeBoundary, "", "#444444", true, nil},
		{"outside", RoleOutside, "", ShapeOval, "", "#999999", true, nil},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			s := StyleFor(tt.role, tt.kind, nil)
			if s.Shape != tt.shape || s.Fill != tt.fill || s.Stroke != tt.stroke || s.Dashed != tt.dashed {
				t.Errorf("StyleFor(%s,%s) = %+v", tt.role, tt.kind, s)
			}
			if !reflect.DeepEqual(s.Classes, tt.wantClasses) {
				t.Errorf("classes = %v, want %v", s.Classes, tt.wantClasses)
			}
		})
	}
}

func TestStyleForTagsAndDeterminism(t *testing.T) {
	t.Parallel()
	a := StyleFor(RoleElement, KindContainer, []string{"pci", "a b", "edge"})
	b := StyleFor(RoleElement, KindContainer, []string{"pci", "a b", "edge"})
	want := []string{"kind-container", "tag-a_20b", "tag-edge", "tag-pci"}
	if !reflect.DeepEqual(a.Classes, want) {
		t.Errorf("classes = %v, want %v", a.Classes, want)
	}
	if !reflect.DeepEqual(a, b) {
		t.Error("StyleFor is not deterministic (FR-019)")
	}
	if a.FontColor == "" {
		t.Error("filled element must carry a font colour")
	}
}

func TestFormats(t *testing.T) {
	t.Parallel()
	got, err := ParseFormats([]string{"svg,d2", "svg", " html "})
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, []Format{FormatD2, FormatSVG, FormatHTML}) {
		t.Errorf("ParseFormats = %v", got)
	}
	for _, bad := range []string{"pdf", "mermaid"} {
		_, err := ParseFormats([]string{"d2," + bad})
		want := `unsupported format "` + bad + `": supported formats are d2, svg, md, html`
		if err == nil || err.Error() != want {
			t.Errorf("ParseFormats(%s) err = %v, want %q", bad, err, want)
		}
	}
	if _, err := ParseFormats(nil); err == nil {
		t.Error("an empty format list must be rejected")
	}

	expanded, added := Expand([]Format{FormatHTML})
	if !reflect.DeepEqual(expanded, []Format{FormatSVG, FormatHTML}) || !reflect.DeepEqual(added, []Format{FormatSVG}) {
		t.Errorf("Expand(html) = %v added %v", expanded, added)
	}
	expanded, added = Expand([]Format{FormatSVG, FormatMD})
	if !reflect.DeepEqual(expanded, []Format{FormatSVG, FormatMD}) || added != nil {
		t.Errorf("Expand(svg,md) = %v added %v", expanded, added)
	}
}

func TestNoticeText(t *testing.T) {
	t.Parallel()
	got := NoticeText([]string{"b.loko.hcl", "a.loko.hcl", "b.loko.hcl"})
	want := "Code generated by loko from a.loko.hcl, b.loko.hcl. DO NOT EDIT."
	if got != want {
		t.Errorf("NoticeText = %q, want %q", got, want)
	}
	if got := NoticeText(nil); got != "Code generated by loko. DO NOT EDIT." {
		t.Errorf("NoticeText(nil) = %q", got)
	}
	defer func() {
		if recover() == nil {
			t.Error("an absolute source path must panic: provenance is always project-relative")
		}
	}()
	NoticeText([]string{"/abs/x.loko.hcl"})
}

func TestSortArtifacts(t *testing.T) {
	t.Parallel()
	as := []Artifact{{Path: "b"}, {Path: "a/z"}, {Path: "a"}}
	SortArtifacts(as)
	if as[0].Path != "a" || as[1].Path != "a/z" || as[2].Path != "b" {
		t.Errorf("SortArtifacts = %v", as)
	}
}
