// Command genfixture writes a synthetic loko project of a requested size.
//
// It exists for the performance bounds in SC-006 — 1,000 elements across 200
// files under 2 seconds, 5,000 under 10 — which cannot be measured against the
// hand-written fixtures without committing megabytes of generated source.
//
// Output is deterministic for a given size, so two runs produce identical
// trees and a timing comparison is not confounded by a different shape.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	os.Exit(run())
}

func run() int {
	elements := flag.Int("elements", 1000, "Total number of logical elements to generate")
	files := flag.Int("files", 200, "Number of *.loko.hcl files to spread them across")
	out := flag.String("out", "", "Directory to write into (required; created if absent)")
	envs := flag.Int("deployments", 2, "Number of deployment environments")
	flag.Parse()

	if *out == "" {
		fmt.Fprintln(os.Stderr, "genfixture: -out is required")
		return 2
	}
	if *elements < 1 || *files < 1 || *files > *elements {
		fmt.Fprintln(os.Stderr, "genfixture: need elements >= files >= 1")
		return 2
	}

	if err := generate(*out, *elements, *files, *envs); err != nil {
		fmt.Fprintf(os.Stderr, "genfixture: %v\n", err)
		return 1
	}
	fmt.Printf("wrote %d elements across %d files to %s\n", *elements, *files, *out)
	return 0
}

// generate lays out systems, containers and components in a fixed ratio so the
// shape is realistic: roughly one system per ten containers, and one component
// per container.
func generate(out string, elements, files, envs int) error {
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}

	systems := max(elements/12, 1)
	containers := (elements - systems) / 2
	components := elements - systems - containers

	decls := make([]string, 0, elements)
	decls = append(decls, declareSystems(systems)...)
	decls = append(decls, declareContainers(containers, systems)...)
	decls = append(decls, declareComponents(components, containers)...)

	if err := writeSharded(out, decls, files); err != nil {
		return err
	}
	return writeDeployments(out, envs, containers)
}

func declareSystems(n int) []string {
	out := make([]string, 0, n)
	for i := range n {
		out = append(out, fmt.Sprintf(
			"system \"sys_%d\" {\n  description = \"Synthetic system %d\"\n  owner       = \"team_%d\"\n}\n",
			i, i, i%7))
	}
	return out
}

func declareContainers(n, systems int) []string {
	out := make([]string, 0, n)
	for i := range n {
		// Each container uses the next one, which produces a realistic edge
		// density and exercises resolution across file boundaries.
		target := (i + 1) % n
		out = append(out, fmt.Sprintf(
			"container \"con_%d\" {\n  system     = system.sys_%d\n  technology = \"Go\"\n  tags       = [\"tier_%d\"]\n\n  uses \"next\" {\n    target = container.con_%d\n  }\n}\n",
			i, i%systems, i%3, target))
	}
	return out
}

func declareComponents(n, containers int) []string {
	out := make([]string, 0, n)
	for i := range n {
		out = append(out, fmt.Sprintf(
			"component \"cmp_%d\" {\n  container   = container.con_%d\n  description = \"Synthetic component %d\"\n}\n",
			i, i%containers, i))
	}
	return out
}

// writeSharded spreads declarations across files as evenly as possible, in
// nested directories, so discovery is exercised too.
func writeSharded(out string, decls []string, files int) error {
	perFile := (len(decls) + files - 1) / files

	for f := range files {
		lo := f * perFile
		if lo >= len(decls) {
			break
		}
		hi := min(lo+perFile, len(decls))

		var b strings.Builder
		if f == 0 {
			b.WriteString("project \"synthetic\" {\n  description  = \"Generated by tools/genfixture\"\n  loko_version = \"~> 1.0\"\n}\n\n")
		}
		b.WriteString(strings.Join(decls[lo:hi], "\n"))

		dir := filepath.Join(out, fmt.Sprintf("group_%02d", f%10))
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		path := filepath.Join(dir, fmt.Sprintf("part_%04d.loko.hcl", f))
		if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func writeDeployments(out string, envs, containers int) error {
	if envs < 1 {
		return nil
	}
	var b strings.Builder
	for e := range envs {
		fmt.Fprintf(&b, "deployment \"env_%d\" {\n  provider = \"aws\"\n  region   = \"us-east-1\"\n\n  node \"vpc\" {\n", e)
		// One instance per ten containers keeps the deployment plane
		// meaningful without doubling the element count.
		for i := 0; i < containers; i += 10 {
			fmt.Fprintf(&b,
				"    instance \"inst_%d\" {\n      of = container.con_%d\n      binding \"terraform\" {\n        address = \"module.m%d.aws_lambda_function.this\"\n      }\n    }\n",
				i, i, i)
		}
		b.WriteString("  }\n}\n\n")
	}
	return os.WriteFile(filepath.Join(out, "deployments.loko.hcl"), []byte(b.String()), 0o644)
}
