package outputdir

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
	"time"

	vm "github.com/madstone-tech/loko/internal/core/entities/viewmodel"
	"github.com/madstone-tech/loko/internal/core/usecases"
)

var _ usecases.ArtifactStore = (*Store)(nil)

func art(path, body string) vm.Artifact { return vm.Artifact{Path: path, Bytes: []byte(body)} }

func read(t *testing.T, p string) string {
	t.Helper()
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func noStaging(t *testing.T, dir string) {
	t.Helper()
	matches, _ := filepath.Glob(filepath.Join(dir, ".loko-staging-*"))
	if len(matches) > 0 {
		t.Errorf("staging directory left behind: %v", matches)
	}
}

// ---- T029: basic commit ----

func TestCommitCreatesAndWrites(t *testing.T) {
	t.Parallel()
	out := filepath.Join(t.TempDir(), "dist")
	rep, err := New().Commit(context.Background(), out,
		[]vm.Artifact{art("index.html", "i"), art("diagrams/a.svg", "a")}, []string{"main.loko.hcl"})
	if err != nil {
		t.Fatal(err)
	}
	if read(t, filepath.Join(out, "index.html")) != "i" || read(t, filepath.Join(out, "diagrams", "a.svg")) != "a" {
		t.Error("artifacts not written")
	}
	if !reflect.DeepEqual(rep.Written, []string{"diagrams/a.svg", "index.html"}) {
		t.Errorf("Written = %v", rep.Written)
	}
	noStaging(t, out)
}

func TestCommitUnwritableDirectory(t *testing.T) {
	if runtime.GOOS == "windows" || os.Geteuid() == 0 {
		t.Skip("permission bits are not enforced here")
	}
	t.Parallel()
	out := filepath.Join(t.TempDir(), "dist")
	if err := os.MkdirAll(out, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(out, 0o500); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(out, 0o755) })

	_, err := New().Commit(context.Background(), out, []vm.Artifact{art("a.svg", "a")}, nil)
	if err == nil || !strings.Contains(err.Error(), out) {
		t.Fatalf("err = %v, want an error naming %s", err, out)
	}
	entries, _ := os.ReadDir(out)
	if len(entries) != 0 {
		t.Errorf("partially written: %v", entries)
	}
}

// ---- T043: manifest, skip-identical, prune ----

func TestManifestWrittenLast(t *testing.T) {
	t.Parallel()
	out := t.TempDir()
	if _, err := New().Commit(context.Background(), out, []vm.Artifact{art("b", "1"), art("a", "2")}, []string{"x.loko.hcl"}); err != nil {
		t.Fatal(err)
	}
	want := "# Code generated by loko from x.loko.hcl. DO NOT EDIT.\na\nb\n"
	if got := read(t, filepath.Join(out, vm.ManifestFile)); got != want {
		t.Errorf("manifest = %q, want %q", got, want)
	}
}

func TestCommitSkipsIdenticalFiles(t *testing.T) {
	t.Parallel()
	out := t.TempDir()
	s := New()
	as := []vm.Artifact{art("a.svg", "a"), art("b.svg", "b")}
	if _, err := s.Commit(context.Background(), out, as, nil); err != nil {
		t.Fatal(err)
	}
	old := time.Now().Add(-time.Hour).Truncate(time.Second)
	for _, p := range []string{"a.svg", "b.svg"} {
		if err := os.Chtimes(filepath.Join(out, p), old, old); err != nil {
			t.Fatal(err)
		}
	}
	rep, err := s.Commit(context.Background(), out, []vm.Artifact{art("a.svg", "a"), art("b.svg", "B")}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(rep.Unchanged, []string{"a.svg"}) || !reflect.DeepEqual(rep.Written, []string{"b.svg"}) {
		t.Errorf("report = %+v", rep)
	}
	st, err := os.Stat(filepath.Join(out, "a.svg"))
	if err != nil {
		t.Fatal(err)
	}
	if !st.ModTime().Equal(old) {
		t.Errorf("unchanged file was rewritten: mtime %v, want %v (FR-022)", st.ModTime(), old)
	}
}

func TestCommitPrunesOnlyOwnedFiles(t *testing.T) {
	t.Parallel()
	out := t.TempDir()
	s := New()
	if _, err := s.Commit(context.Background(), out,
		[]vm.Artifact{art("keep.svg", "k"), art("element/container/gone.html", "g")}, nil); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(out, "NOTES.txt"), []byte("mine"), 0o644); err != nil {
		t.Fatal(err)
	}
	rep, err := s.Commit(context.Background(), out, []vm.Artifact{art("keep.svg", "k")}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(rep.Removed, []string{"element/container/gone.html"}) {
		t.Errorf("Removed = %v", rep.Removed)
	}
	if _, err := os.Stat(filepath.Join(out, "element", "container", "gone.html")); !os.IsNotExist(err) {
		t.Error("orphan not removed (FR-023)")
	}
	if _, err := os.Stat(filepath.Join(out, "element")); !os.IsNotExist(err) {
		t.Error("directories emptied by pruning should be removed")
	}
	if read(t, filepath.Join(out, "NOTES.txt")) != "mine" {
		t.Error("a file the tool did not generate was touched")
	}
}

func TestCommitWithoutManifestPrunesNothing(t *testing.T) {
	t.Parallel()
	out := t.TempDir()
	if err := os.WriteFile(filepath.Join(out, "old.svg"), []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(out, vm.ManifestFile), []byte("garbage\x00\n../../etc/passwd\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	rep, err := New().Commit(context.Background(), out, []vm.Artifact{art("new.svg", "n")}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(rep.Removed) != 0 {
		t.Errorf("Removed = %v, want nothing from a corrupt manifest", rep.Removed)
	}
	if _, err := os.Stat(filepath.Join(out, "old.svg")); err != nil {
		t.Error("unowned file removed")
	}
}
