package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestBuildNotice is FR-020 and SC-004: every generated file, in every format
// and every fixture, says within its first two lines that it is generated,
// must not be edited, and which authored files it came from.
func TestBuildNotice(t *testing.T) {
	t.Parallel()
	for _, name := range buildableFixtures(t) {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			root := filepath.Join(fixtures, name)
			out := t.TempDir()
			runBuildIn(t, root, out)
			for _, f := range listFiles(t, out) {
				data := readString(t, filepath.Join(out, filepath.FromSlash(f)))
				head := strings.Join(firstLines(data, 2), "\n")
				i := strings.Index(head, "Code generated by loko")
				if i < 0 || !strings.Contains(head[i:], "DO NOT EDIT.") {
					t.Errorf("%s: no generated-file notice in its first two lines:\n%.200s", f, head)
					continue
				}
				for _, src := range noticeSources(head[i:]) {
					if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(src))); err != nil {
						t.Errorf("%s: notice names %q, which does not exist in the project", f, src)
					}
				}
			}
		})
	}
}

func firstLines(s string, n int) []string {
	lines := strings.SplitN(s, "\n", n+1)
	if len(lines) > n {
		lines = lines[:n]
	}
	return lines
}

// noticeSources extracts the file list from "Code generated by loko from a,
// b. DO NOT EDIT."
func noticeSources(notice string) []string {
	const from = "Code generated by loko from "
	if !strings.HasPrefix(notice, from) {
		return nil
	}
	list, _, _ := strings.Cut(strings.TrimPrefix(notice, from), ". DO NOT EDIT.")
	return strings.Split(list, ", ")
}
