package html

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	vm "github.com/madstone-tech/loko/internal/core/entities/viewmodel"
	"github.com/madstone-tech/loko/internal/core/usecases"
)

var update = flag.Bool("update", false, "rewrite golden files from current behaviour")

var _ usecases.Backend = (*Backend)(nil)

func loadProjection(t *testing.T) *vm.Projection {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "testdata", "projects", "two-systems", "expected", "projection.json"))
	if err != nil {
		t.Fatal(err)
	}
	var p vm.Projection
	if err := json.Unmarshal(data, &p); err != nil {
		t.Fatal(err)
	}
	return &p
}

func renderSite(t *testing.T, proj *vm.Projection, theme []vm.ThemeFile) map[string]string {
	t.Helper()
	as, err := New().Render(context.Background(), proj, usecases.RenderOptions{Theme: theme})
	if err != nil {
		t.Fatal(err)
	}
	out := map[string]string{}
	for _, a := range as {
		out[a.Path] = string(a.Bytes)
	}
	return out
}

func TestSiteGolden(t *testing.T) {
	t.Parallel()
	proj := loadProjection(t)
	first, second := renderSite(t, proj, nil), renderSite(t, proj, nil)
	for path, body := range first {
		if second[path] != body {
			t.Errorf("%s differs between renders (FR-021)", path)
		}
		golden(t, filepath.Join("testdata", "golden", filepath.FromSlash(path)), []byte(body))
	}
}

func TestSiteStructure(t *testing.T) {
	t.Parallel()
	proj := loadProjection(t)
	out := renderSite(t, proj, nil)

	for _, p := range []string{"index.html", "view/landscape.html", "element/container/api.html",
		"assets/style.css", "assets/custom.css", "assets/site.js", "assets/search-index.js"} {
		if _, ok := out[p]; !ok {
			t.Errorf("missing %s", p)
		}
	}
	for path, body := range out {
		lines := strings.SplitN(body, "\n", 3)
		switch {
		case strings.HasSuffix(path, ".html"):
			if lines[0] != "<!DOCTYPE html>" || !strings.HasPrefix(lines[1], "<!-- Code generated by loko") {
				t.Errorf("%s: doctype must be line 1 and the notice line 2; got %q", path, lines[:2])
			}
		default:
			if !strings.HasPrefix(lines[0], "/* Code generated by loko") {
				t.Errorf("%s: line 1 is not the notice: %q", path, lines[0])
			}
		}
		if strings.Contains(body, "/_loko/") || strings.Contains(body, "EventSource") {
			t.Errorf("%s contains live-reload code; that is injected only by serve", path)
		}
	}

	api := out["element/container/api.html"]
	for _, want := range []string{
		`<img src="../../diagrams/container-api.svg"`,
		`Prose for <strong>api</strong>`,
		`<a href="../../element/container/gateway.html">gateway</a>`,
		`class="page-element kind-container"`,
	} {
		if !strings.Contains(api, want) {
			t.Errorf("api page lacks %q", want)
		}
	}
	if !strings.Contains(out["element/container/web.html"], "tag-edge") {
		t.Error("tags are not carried as classes (FR-018)")
	}
	if !strings.Contains(out["element/container/fraud.html"], `Prose file <code>./docs/missing-fraud.md</code> not found.`) {
		t.Error("missing prose not noted (FR-026)")
	}
}

func TestSiteEscapesDescriptions(t *testing.T) {
	t.Parallel()
	proj := loadProjection(t)
	proj.Pages[0].Description = `<b>bold</b> & "quoted"`
	body := renderSite(t, proj, nil)[proj.Pages[0].PagePath]
	if strings.Contains(body, "<b>bold</b>") {
		t.Error("descriptions must be escaped (html/template)")
	}
}

func golden(t *testing.T, path string, got []byte) {
	t.Helper()
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading golden (run with -update to create): %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s differs from golden; inspect, then run with -update", path)
	}
}
