package html

// templateMap contains all HTML templates used for site generation.
var templateMap = map[string]string{
	"index.html":  indexTemplate,
	"system.html": systemTemplate,
	"base.html":   baseTemplate,
}

// baseTemplate is the base layout template used by all pages.
const baseTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{.Title}} - {{.Project.Name}}</title>
	<link rel="stylesheet" href="/styles/style.css">
</head>
<body>
	<div class="container">
		<aside class="sidebar">
			<div class="sidebar-header">
				<h1><a href="/">{{.Project.Name}}</a></h1>
			</div>
			<nav class="sidebar-nav">
				<div class="search-box">
					<input type="text" id="search" placeholder="Search..." class="search-input">
				</div>
				<ul class="system-list">
					{{range .Systems}}
					<li>
						<a href="/systems/{{.ID}}.html" class="system-link">{{.Name}}</a>
						{{if .Containers}}
						<ul class="container-list">
							{{range .Containers}}
							<li><a href="/systems/{{.ParentID}}.html#{{.ID}}" class="container-link">{{.Name}}</a></li>
							{{end}}
						</ul>
						{{end}}
					</li>
					{{end}}
				</ul>
			</nav>
		</aside>
		<main class="main-content">
			{{template "content" .}}
			<footer class="footer">
				<p>Generated by <a href="https://github.com/madstone-tech/loko">loko</a></p>
			</footer>
		</main>
	</div>
	<script src="/js/main.js"></script>
</body>
</html>`

// indexTemplate is the project index page template.
const indexTemplate = `{{define "index.html"}}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{.Project.Name}} - Architecture Documentation</title>
	<link rel="stylesheet" href="styles/style.css">
</head>
<body>
	<div class="container">
		<aside class="sidebar">
			<div class="sidebar-header">
				<h1><a href="index.html">{{.Project.Name}}</a></h1>
			</div>
			<nav class="sidebar-nav">
				<div class="search-box">
					<input type="text" id="search" placeholder="Search..." class="search-input">
				</div>
				<ul class="system-list">
					{{range .Systems}}
					{{if .}}
					<li>
						<a href="systems/{{.ID}}.html" class="system-link">{{.Name}}</a>
						{{if .Containers}}
						<ul class="container-list">
							{{range .Containers}}
							<li><a href="systems/{{.ParentID}}.html#{{.ID}}" class="container-link">{{.Name}}</a></li>
							{{end}}
						</ul>
						{{end}}
					</li>
					{{end}}
					{{end}}
				</ul>
			</nav>
		</aside>
		<main class="main-content">
			<div class="breadcrumb">
				<span class="breadcrumb-item active">Home</span>
			</div>
			<article class="content">
				<h1>{{.Project.Name}}</h1>
				{{if .Project.Description}}
				<p class="description">{{.Project.Description}}</p>
				{{end}}
				{{if .Project.Version}}
				<p class="version">Version: <code>{{.Project.Version}}</code></p>
				{{end}}

				<section class="systems-section">
					<h2>Systems</h2>
					{{if .Systems}}
					<div class="systems-grid">
						{{range .Systems}}
						{{if .}}
						<div class="system-card">
							<h3><a href="systems/{{.ID}}.html">{{.Name}}</a></h3>
							{{if .Description}}
							<p>{{.Description}}</p>
							{{end}}
							{{if .Tags}}
							<div class="tags">
								{{range .Tags}}
								<span class="tag">{{.}}</span>
								{{end}}
							</div>
							{{end}}
							{{if .Containers}}
							<p class="container-count">{{len .Containers}} container{{if ne (len .Containers) 1}}s{{end}}</p>
							{{end}}
						</div>
						{{end}}
						{{end}}
					</div>
					{{else}}
					<p class="empty-state">No systems found.</p>
					{{end}}
				</section>

				<section class="stats-section">
					<h2>Statistics</h2>
					<div class="stats-grid">
						<div class="stat-card">
							<div class="stat-value">{{len .Systems}}</div>
							<div class="stat-label">Systems</div>
						</div>
						<div class="stat-card">
							<div class="stat-value">{{.Project.ContainerCount}}</div>
							<div class="stat-label">Containers</div>
						</div>
						<div class="stat-card">
							<div class="stat-value">{{.Project.ComponentCount}}</div>
							<div class="stat-label">Components</div>
						</div>
					</div>
				</section>
			</article>
			<footer class="footer">
				<p>Generated by <a href="https://github.com/madstone-tech/loko">loko</a></p>
			</footer>
		</main>
	</div>
	<script src="js/main.js"></script>
</body>
</html>
{{end}}`

// systemTemplate is the system detail page template.
const systemTemplate = `{{define "system.html"}}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{.System.Name}} - Architecture Documentation</title>
	<link rel="stylesheet" href="../styles/style.css">
</head>
<body>
	<div class="container">
		<aside class="sidebar">
			<div class="sidebar-header">
				<h1><a href="../index.html">{{.System.Name}}</a></h1>
			</div>
			<nav class="sidebar-nav">
				<div class="search-box">
					<input type="text" id="search" placeholder="Search..." class="search-input">
				</div>
				<ul class="system-list">
					<li class="active">
						<a href="#" class="system-link">{{.System.Name}}</a>
						{{if .Containers}}
						<ul class="container-list">
							{{range .Containers}}
							<li><a href="#{{.ID}}" class="container-link">{{.Name}}</a></li>
							{{end}}
						</ul>
						{{end}}
					</li>
				</ul>
			</nav>
		</aside>
		<main class="main-content">
			<div class="breadcrumb">
				<a href="../index.html" class="breadcrumb-item">Home</a>
				<span class="breadcrumb-separator">/</span>
				<span class="breadcrumb-item active">{{.System.Name}}</span>
			</div>
			<article class="content">
				<h1>{{.System.Name}}</h1>
				{{if .System.Description}}
				<p class="description">{{.System.Description}}</p>
				{{end}}

				{{if .System.Tags}}
				<div class="tags">
					{{range .System.Tags}}
					<span class="tag">{{.}}</span>
					{{end}}
				</div>
				{{end}}

			{{if .System.Diagram}}
			<section class="diagram-section">
				<h2>System Diagram</h2>
				<div class="diagram-container">
					{{if .System.DiagramPath}}
					<img src="../{{.System.DiagramPath}}" alt="{{.System.Name}} Diagram" class="diagram-image">
					{{else}}
					<p class="diagram-placeholder">Diagram: {{.System.Diagram.ID}}</p>
					{{end}}
				</div>
			</section>
			{{end}}

				{{if .Containers}}
				<section class="containers-section">
					<h2>Containers</h2>
					<div class="containers-list">
						{{range .Containers}}
						<div class="container-item" id="{{.ID}}">
							<h3>{{.Name}}</h3>
							{{if .Description}}
							<p>{{.Description}}</p>
							{{end}}
							{{if .Technology}}
							<p class="technology"><strong>Technology:</strong> <code>{{.Technology}}</code></p>
							{{end}}
							{{if .Tags}}
							<div class="tags">
								{{range .Tags}}
								<span class="tag">{{.}}</span>
								{{end}}
							</div>
							{{end}}
						{{if .Diagram}}
						<div class="diagram-container">
							{{if .DiagramPath}}
							<img src="../{{.DiagramPath}}" alt="{{.Name}} Diagram" class="diagram-image">
							{{else}}
							<p class="diagram-placeholder">Diagram: {{.Diagram.ID}}</p>
							{{end}}
						</div>
						{{end}}
							{{if .Components}}
							<div class="components-list">
								<h4>Components</h4>
								<ul>
									{{range .Components}}
									<li>
										<strong>{{.Name}}</strong>
										{{if .Description}}<p>{{.Description}}</p>{{end}}
									</li>
									{{end}}
								</ul>
							</div>
							{{end}}
						</div>
						{{end}}
					</div>
				</section>
				{{else}}
				<p class="empty-state">No containers found in this system.</p>
				{{end}}
			</article>
			<footer class="footer">
				<p>Generated by <a href="https://github.com/madstone-tech/loko">loko</a></p>
			</footer>
		</main>
	</div>
	<script src="../js/main.js"></script>
</body>
</html>
{{end}}`

// cssContent contains the embedded CSS stylesheet.
const cssContent = `/* Global Styles */
:root {
	--color-primary: #2563eb;
	--color-primary-dark: #1e40af;
	--color-primary-light: #dbeafe;
	--color-text: #1f2937;
	--color-text-light: #6b7280;
	--color-bg: #ffffff;
	--color-bg-alt: #f9fafb;
	--color-border: #e5e7eb;
	--color-success: #10b981;
	--color-warning: #f59e0b;
	--color-error: #ef4444;
	--spacing-xs: 0.25rem;
	--spacing-sm: 0.5rem;
	--spacing-md: 1rem;
	--spacing-lg: 1.5rem;
	--spacing-xl: 2rem;
	--spacing-2xl: 3rem;
	--font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
	--font-mono: "Menlo", "Monaco", "Courier New", monospace;
	--border-radius: 0.375rem;
	--shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
	--shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
	--shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
}

@media (prefers-color-scheme: dark) {
	:root {
		--color-text: #f3f4f6;
		--color-text-light: #d1d5db;
		--color-bg: #111827;
		--color-bg-alt: #1f2937;
		--color-border: #374151;
		--color-primary-light: #1e3a8a;
	}
}

* {
	margin: 0;
	padding: 0;
	box-sizing: border-box;
}

html {
	font-size: 16px;
	scroll-behavior: smooth;
}

body {
	font-family: var(--font-family);
	color: var(--color-text);
	background-color: var(--color-bg);
	line-height: 1.6;
}

/* Layout */
.container {
	display: flex;
	min-height: 100vh;
}

.sidebar {
	width: 280px;
	background-color: var(--color-bg-alt);
	border-right: 1px solid var(--color-border);
	overflow-y: auto;
	position: sticky;
	top: 0;
	max-height: 100vh;
}

.sidebar-header {
	padding: var(--spacing-lg);
	border-bottom: 1px solid var(--color-border);
}

.sidebar-header h1 {
	font-size: 1.25rem;
	font-weight: 700;
	margin: 0;
}

.sidebar-header a {
	color: var(--color-primary);
	text-decoration: none;
}

.sidebar-header a:hover {
	color: var(--color-primary-dark);
}

.sidebar-nav {
	padding: var(--spacing-lg);
}

.search-box {
	margin-bottom: var(--spacing-lg);
}

.search-input {
	width: 100%;
	padding: var(--spacing-sm) var(--spacing-md);
	border: 1px solid var(--color-border);
	border-radius: var(--border-radius);
	font-family: var(--font-family);
	font-size: 0.875rem;
	background-color: var(--color-bg);
	color: var(--color-text);
}

.search-input:focus {
	outline: none;
	border-color: var(--color-primary);
	box-shadow: 0 0 0 3px var(--color-primary-light);
}

.system-list {
	list-style: none;
}

.system-list > li {
	margin-bottom: var(--spacing-md);
}

.system-link {
	display: block;
	padding: var(--spacing-sm) var(--spacing-md);
	color: var(--color-text);
	text-decoration: none;
	border-radius: var(--border-radius);
	font-weight: 500;
	transition: background-color 0.2s;
}

.system-link:hover {
	background-color: var(--color-border);
	color: var(--color-primary);
}

.system-list .active .system-link {
	background-color: var(--color-primary-light);
	color: var(--color-primary);
}

.container-list {
	list-style: none;
	margin-top: var(--spacing-sm);
	margin-left: var(--spacing-md);
	padding-left: var(--spacing-md);
	border-left: 2px solid var(--color-border);
}

.container-list li {
	margin-bottom: var(--spacing-xs);
}

.container-link {
	display: block;
	padding: var(--spacing-xs) var(--spacing-md);
	color: var(--color-text-light);
	text-decoration: none;
	font-size: 0.875rem;
	border-radius: var(--border-radius);
	transition: color 0.2s;
}

.container-link:hover {
	color: var(--color-primary);
}

/* Main Content */
.main-content {
	flex: 1;
	overflow-y: auto;
	padding: var(--spacing-2xl);
}

.breadcrumb {
	display: flex;
	align-items: center;
	gap: var(--spacing-sm);
	margin-bottom: var(--spacing-xl);
	font-size: 0.875rem;
	color: var(--color-text-light);
}

.breadcrumb-item {
	color: var(--color-text-light);
}

.breadcrumb-item.active {
	color: var(--color-text);
	font-weight: 500;
}

.breadcrumb-item a {
	color: var(--color-primary);
	text-decoration: none;
}

.breadcrumb-item a:hover {
	text-decoration: underline;
}

.breadcrumb-separator {
	color: var(--color-border);
}

.content {
	max-width: 900px;
}

.content h1 {
	font-size: 2.25rem;
	font-weight: 700;
	margin-bottom: var(--spacing-md);
	color: var(--color-text);
}

.content h2 {
	font-size: 1.875rem;
	font-weight: 600;
	margin-top: var(--spacing-2xl);
	margin-bottom: var(--spacing-lg);
	color: var(--color-text);
}

.content h3 {
	font-size: 1.25rem;
	font-weight: 600;
	margin-top: var(--spacing-lg);
	margin-bottom: var(--spacing-md);
	color: var(--color-text);
}

.content h4 {
	font-size: 1rem;
	font-weight: 600;
	margin-top: var(--spacing-md);
	margin-bottom: var(--spacing-sm);
	color: var(--color-text);
}

.content p {
	margin-bottom: var(--spacing-md);
	color: var(--color-text);
}

.description {
	font-size: 1.125rem;
	color: var(--color-text-light);
	margin-bottom: var(--spacing-lg);
}

.version {
	color: var(--color-text-light);
	font-size: 0.875rem;
}

/* Tags */
.tags {
	display: flex;
	flex-wrap: wrap;
	gap: var(--spacing-sm);
	margin: var(--spacing-md) 0;
}

.tag {
	display: inline-block;
	padding: var(--spacing-xs) var(--spacing-md);
	background-color: var(--color-primary-light);
	color: var(--color-primary);
	border-radius: var(--border-radius);
	font-size: 0.75rem;
	font-weight: 500;
	text-transform: uppercase;
	letter-spacing: 0.5px;
}

/* Cards */
.systems-grid {
	display: grid;
	grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
	gap: var(--spacing-lg);
	margin-bottom: var(--spacing-2xl);
}

.system-card {
	padding: var(--spacing-lg);
	background-color: var(--color-bg-alt);
	border: 1px solid var(--color-border);
	border-radius: var(--border-radius);
	transition: box-shadow 0.2s, transform 0.2s;
}

.system-card:hover {
	box-shadow: var(--shadow-md);
	transform: translateY(-2px);
}

.system-card h3 {
	margin-top: 0;
	margin-bottom: var(--spacing-md);
}

.system-card a {
	color: var(--color-primary);
	text-decoration: none;
}

.system-card a:hover {
	text-decoration: underline;
}

.system-card p {
	margin-bottom: var(--spacing-md);
	color: var(--color-text-light);
}

.container-count {
	font-size: 0.875rem;
	color: var(--color-text-light);
	margin-top: var(--spacing-md);
}

/* Statistics */
.stats-section {
	margin-top: var(--spacing-2xl);
}

.stats-grid {
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
	gap: var(--spacing-lg);
	margin-top: var(--spacing-lg);
}

.stat-card {
	padding: var(--spacing-lg);
	background-color: var(--color-bg-alt);
	border: 1px solid var(--color-border);
	border-radius: var(--border-radius);
	text-align: center;
}

.stat-value {
	font-size: 2rem;
	font-weight: 700;
	color: var(--color-primary);
	margin-bottom: var(--spacing-sm);
}

.stat-label {
	font-size: 0.875rem;
	color: var(--color-text-light);
	text-transform: uppercase;
	letter-spacing: 0.5px;
}

/* Containers */
.containers-section {
	margin-top: var(--spacing-2xl);
}

.containers-list {
	display: flex;
	flex-direction: column;
	gap: var(--spacing-xl);
}

.container-item {
	padding: var(--spacing-lg);
	background-color: var(--color-bg-alt);
	border: 1px solid var(--color-border);
	border-radius: var(--border-radius);
	scroll-margin-top: 100px;
}

.container-item h3 {
	margin-top: 0;
}

.technology {
	font-size: 0.875rem;
	color: var(--color-text-light);
}

.technology code {
	background-color: var(--color-bg);
	padding: var(--spacing-xs) var(--spacing-sm);
	border-radius: var(--border-radius);
	font-family: var(--font-mono);
	color: var(--color-primary);
}

/* Diagrams */
.diagram-section {
	margin-top: var(--spacing-2xl);
}

.diagram-container {
	margin: var(--spacing-lg) 0;
	padding: var(--spacing-lg);
	background-color: var(--color-bg-alt);
	border: 1px solid var(--color-border);
	border-radius: var(--border-radius);
	min-height: 300px;
	display: flex;
	align-items: center;
	justify-content: center;
}

.diagram-placeholder {
	color: var(--color-text-light);
	font-style: italic;
}

.diagram-image {
	max-width: 100%;
	height: auto;
	object-fit: contain;
}

/* Components */
.components-list {
	margin-top: var(--spacing-lg);
	padding-top: var(--spacing-lg);
	border-top: 1px solid var(--color-border);
}

.components-list h4 {
	margin-top: 0;
}

.components-list ul {
	list-style: none;
	padding: 0;
}

.components-list li {
	padding: var(--spacing-md) 0;
	border-bottom: 1px solid var(--color-border);
}

.components-list li:last-child {
	border-bottom: none;
}

.components-list strong {
	color: var(--color-text);
	display: block;
	margin-bottom: var(--spacing-xs);
}

.components-list p {
	margin: 0;
	font-size: 0.875rem;
	color: var(--color-text-light);
}

/* Empty State */
.empty-state {
	padding: var(--spacing-2xl);
	text-align: center;
	color: var(--color-text-light);
	background-color: var(--color-bg-alt);
	border-radius: var(--border-radius);
	border: 1px dashed var(--color-border);
}

/* Footer */
.footer {
	margin-top: var(--spacing-2xl);
	padding-top: var(--spacing-lg);
	border-top: 1px solid var(--color-border);
	text-align: center;
	font-size: 0.875rem;
	color: var(--color-text-light);
}

.footer a {
	color: var(--color-primary);
	text-decoration: none;
}

.footer a:hover {
	text-decoration: underline;
}

/* Code */
code {
	font-family: var(--font-mono);
	font-size: 0.875em;
	background-color: var(--color-bg-alt);
	padding: var(--spacing-xs) var(--spacing-sm);
	border-radius: var(--border-radius);
	color: var(--color-primary);
}

/* Responsive */
@media (max-width: 768px) {
	.container {
		flex-direction: column;
	}

	.sidebar {
		width: 100%;
		max-height: none;
		position: relative;
		border-right: none;
		border-bottom: 1px solid var(--color-border);
	}

	.main-content {
		padding: var(--spacing-lg);
	}

	.content h1 {
		font-size: 1.875rem;
	}

	.content h2 {
		font-size: 1.5rem;
	}

	.systems-grid {
		grid-template-columns: 1fr;
	}

	.stats-grid {
		grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
	}
}`

// jsContent contains the embedded JavaScript for interactivity.
const jsContent = `// Search functionality
document.addEventListener('DOMContentLoaded', function() {
	const searchInput = document.getElementById('search');
	if (searchInput) {
		searchInput.addEventListener('input', function(e) {
			const query = e.target.value.toLowerCase();
			const items = document.querySelectorAll('.system-link, .container-link');
			
			items.forEach(item => {
				const text = item.textContent.toLowerCase();
				const parent = item.closest('li');
				if (text.includes(query)) {
					parent.style.display = '';
				} else {
					parent.style.display = 'none';
				}
			});
		});
	}
});

// Smooth scroll for anchor links
document.addEventListener('click', function(e) {
	if (e.target.tagName === 'A' && e.target.getAttribute('href').startsWith('#')) {
		e.preventDefault();
		const target = document.querySelector(e.target.getAttribute('href'));
		if (target) {
			target.scrollIntoView({ behavior: 'smooth' });
		}
	}
});

// Back to top button
window.addEventListener('scroll', function() {
	const backToTop = document.querySelector('.back-to-top');
	if (backToTop) {
		if (window.scrollY > 300) {
			backToTop.style.display = 'block';
		} else {
			backToTop.style.display = 'none';
		}
	}
});

// Highlight active navigation item
document.addEventListener('DOMContentLoaded', function() {
	const currentPath = window.location.pathname;
	const navLinks = document.querySelectorAll('.system-link, .container-link');
	
	navLinks.forEach(link => {
		const href = link.getAttribute('href');
		if (href && currentPath.includes(href.replace(/^\//, ''))) {
			link.closest('li').classList.add('active');
		}
	});
});`
