#!/usr/bin/env bash
# coverage-delta.sh — compare per-package coverage against a baseline file and
# fail on regression > tolerance (default 0.5 percentage points).
#
# Usage:
#   ./scripts/coverage-delta.sh [BASELINE_FILE] [TOLERANCE_PP]
#
# Defaults:
#   BASELINE_FILE  specs/010-constitution-compliance/coverage-baseline.txt
#   TOLERANCE_PP   0.5
#
# Baseline format (one package per line, generated by `go tool cover -func`):
#   github.com/madstone-tech/loko/internal/core/entities <tab> total: <tab> NN.N%
#
# Exit codes:
#   0 — every package within tolerance of its baseline
#   1 — at least one package regressed beyond tolerance
#   2 — environment error (missing baseline, go tool failure)

set -euo pipefail

baseline="${1:-specs/010-constitution-compliance/coverage-baseline.txt}"
tolerance="${2:-0.5}"

if [[ ! -f "$baseline" ]]; then
  echo "coverage-delta: baseline file not found: $baseline" >&2
  echo "  Generate one with:" >&2
  echo "    go test -coverprofile=cover.out ./..." >&2
  echo "    go tool cover -func=cover.out > $baseline" >&2
  exit 2
fi

# Generate current per-package coverage in the same format as the baseline
# (<package> <tab> total: <tab> NN.N%), derived from `go test -cover` per-package
# output. (`go tool cover -func` emits per-function and a single global total only,
# so it cannot drive a per-package comparison.)
tmp_current=$(mktemp -t coverage-current.XXXXXX)
trap 'rm -f "$tmp_current"' EXIT

go test -cover ./... 2>/dev/null | awk '
  $1=="ok" && /coverage:/ {
    pct="";
    for (i=1;i<=NF;i++) if ($i=="coverage:") pct=$(i+1)
    if (pct ~ /^[0-9.]+%$/) print $2 "\t" "total:" "\t" pct
  }' > "$tmp_current"

if [[ ! -s "$tmp_current" ]]; then
  echo "coverage-delta: go test produced no coverage output" >&2
  exit 2
fi

regressions=0

# Compare per-package "total:" lines.
while IFS=$'\t' read -r pkg _ pct_base; do
  pkg_clean="${pkg%/}"
  if [[ -z "$pkg_clean" || "$pkg_clean" == "total:" ]]; then
    continue
  fi
  # Extract current pct for the same package.
  pct_curr=$(awk -v p="$pkg_clean" '$1==p && $2=="total:" {print $3}' "$tmp_current")
  if [[ -z "$pct_curr" ]]; then
    continue   # package may have been removed; not flagged here
  fi
  # Strip trailing %.
  base_num="${pct_base%\%}"
  curr_num="${pct_curr%\%}"
  delta=$(awk -v c="$curr_num" -v b="$base_num" 'BEGIN { printf "%.2f", c - b }')
  # Negative delta beyond tolerance is a regression.
  if awk -v d="$delta" -v t="$tolerance" 'BEGIN { exit !(d < -t) }'; then
    echo "REGRESSION: $pkg_clean  baseline=${base_num}%  current=${curr_num}%  delta=${delta}pp  tolerance=-${tolerance}pp" >&2
    regressions=$((regressions + 1))
  fi
done < "$baseline"

if [[ "$regressions" -gt 0 ]]; then
  echo "coverage-delta: $regressions package(s) regressed beyond ${tolerance}pp tolerance" >&2
  exit 1
fi

echo "coverage-delta: OK — no per-package coverage regression beyond ${tolerance}pp"
