package markdown

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	vm "github.com/madstone-tech/loko/internal/core/entities/viewmodel"
	"github.com/madstone-tech/loko/internal/core/usecases"
)

var update = flag.Bool("update", false, "rewrite golden files from current behaviour")

var _ usecases.Backend = (*Backend)(nil)

// loadProjection reads the committed two-systems projection golden, so this
// backend is tested against exactly what the projection produces.
func loadProjection(t *testing.T) *vm.Projection {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "testdata", "projects", "two-systems", "expected", "projection.json"))
	if err != nil {
		t.Fatal(err)
	}
	var p vm.Projection
	if err := json.Unmarshal(data, &p); err != nil {
		t.Fatal(err)
	}
	return &p
}

func render(t *testing.T) map[string]string {
	t.Helper()
	as, err := New().Render(context.Background(), loadProjection(t), usecases.RenderOptions{})
	if err != nil {
		t.Fatal(err)
	}
	out := map[string]string{}
	for _, a := range as {
		if a.Format != vm.FormatMD {
			t.Errorf("%s has format %s", a.Path, a.Format)
		}
		out[a.Path] = string(a.Bytes)
	}
	return out
}

func TestMarkdownGolden(t *testing.T) {
	t.Parallel()
	first, second := render(t), render(t)
	for path, body := range first {
		if second[path] != body {
			t.Errorf("%s differs between renders (FR-021)", path)
		}
		if !strings.HasPrefix(body, "<!-- Code generated by loko") || !strings.Contains(strings.SplitN(body, "\n", 2)[0], "DO NOT EDIT. -->") {
			t.Errorf("%s: line 1 is not the notice", path)
		}
		golden(t, filepath.Join("testdata", "golden", filepath.FromSlash(path)), []byte(body))
	}
}

func TestMarkdownContent(t *testing.T) {
	t.Parallel()
	out := render(t)
	api := out["md/element/container/api.md"]
	for _, want := range []string{
		"# api\n",
		"Prose for **api**.", // prose inlined verbatim
		"![container-api](../../../diagrams/container-api.svg)",
		"| [gateway](gateway.md) | Charges the customer | gRPC |",
		"- [handler](../component/handler.md)",
		"Part of [shop](../system/shop.md)",
	} {
		if !strings.Contains(api, want) {
			t.Errorf("api page lacks %q\n---\n%s", want, api)
		}
	}
	fraud := out["md/element/container/fraud.md"]
	if !strings.Contains(fraud, "Prose file `./docs/missing-fraud.md` not found.") {
		t.Errorf("missing prose is not noted (FR-026)\n%s", fraud)
	}
	index := out["md/index.md"]
	for _, want := range []string{"# two-systems", "![landscape](../diagrams/landscape.svg)", "[shop](element/system/shop.md)", "[deployment-prod](view/deployment-prod.md)"} {
		if !strings.Contains(index, want) {
			t.Errorf("index lacks %q\n%s", want, index)
		}
	}
	staging := out["md/view/deployment-staging.md"]
	if !strings.Contains(staging, "## Leaves this view") {
		t.Errorf("a view with boundary connections lists them\n%s", staging)
	}
}

func golden(t *testing.T, path string, got []byte) {
	t.Helper()
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading golden (run with -update to create): %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s differs from golden; inspect, then run with -update", path)
	}
}
